api/urls.py
from django.urls import path, include
from . import views

app_name = "api"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('docs/', views.docs, name='docs'),
    path('about', views.about, name='about'),
    path('init/', views.GoogleCalendarInitView, name='register'),
    path('redirect/', views.GoogleCalendarRedirectView, name='oauth2callback'),
    
]

googleCalenderApi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest/v1/calendar/', include('api.urls')),
]

api/models.py
from django.db import models

# Create your models here.

api/views.py
from urllib.error import HTTPError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from google_auth_oauthlib.flow import Flow
import os
import os.path
from googleapiclient.discovery import build
import datetime
import json

curr_directory = os.path.dirname(os.path.abspath(__file__))
creds_directory = os.path.join(curr_directory, 'credentials.json')
scopes=['https://www.googleapis.com/auth/userinfo.email','https://www.googleapis.com/auth/userinfo.profile','https://www.googleapis.com/auth/calendar']

def index(request):
    return render(request, 'index.html')

def docs(request):
    return render(request, 'docs.html')

def about(request):
    return render(request, 'about.html')

# view for google oauth login to get access token of the user
def GoogleCalendarInitView(request):
    #Create flow instance to manage the OAuth 2.0 Authorization Grant Flow steps.
    flow = Flow.from_client_secrets_file(
        creds_directory,
        scopes)
    flow.redirect_uri='http://127.0.0.1:8000/rest/v1/calendar/redirect'
    authorization_url, state = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true')
    # Store the state in the session to verify that it is a
    # legitimate request from Google.
    request.session['state'] = state
    return redirect(authorization_url)

def GoogleCalendarRedirectView(request):
    # Specify the state when creating the flow in the callback so that it can verify
    # that the authorization server response is from Google.
    flow = Flow.from_client_secrets_file(
        creds_directory,
        scopes)
    authotization_response = request.get_full_path()
    token = flow.fetch_token(authorization_response=authotization_response)
    credentials = flow.credentials
    try:
        # get events from google calendars with credentials in sessions
        # Create an instance of the Calendar client
        service = build('calendar', 'v3', credentials=credentials)
        # Call the Calendar API
        now = datetime.datetime.utcnow().isoformat() + 'Z' # 'Z' indicates UTC time
        events_results = service.events().list(calendarId='primary', timeMin=now,singleEvents=True,orderBy='startTime').execute()
        events = events_results.get('items', [])
        if not events:
            return HttpResponse({'message':'No upcoming events found.'})
        response_data={}
        for event in events:
            start = event['start'].get('dateTime', event['start'].get('date'))
            response_data[start]=event['summary']
        return HttpResponse(json.dumps(response_data), content_type="application/json")

    except HTTPError as error:
        return HttpResponse({'message':error})


def credentials_to_dict(credentials):
    return {
        'token': credentials.token,
        'refresh_token': credentials.refresh_token,
        'token_uri': credentials.token_uri,
        'client_id': credentials.client_id,
        'client_secret': credentials.client_secret,
        'scopes': credentials.scopes
    }

templates/about.html
{% extends 'layout.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br>
            <br>
            <h1>About Developer</h1>
            <br>
            <br>
            <br>
            <div class="card">
                <div class="card-body">

                    <p>Hi! I am Shrey Sharma and like to solve problem and puzzles. I aim to enhance my skills at
                        coding and apply what I know.</p>
                    <p>I have learnt computer science and fullstack development through online courses
                        and projects.</p>
                    <p>Some of the courses I have done:</p>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h5>
                                <a
                                    href="https://www.freecodecamp.org/certification/Shrey1098/back-end-development-and-apis">
                                    Back End development and APIs
                                </a>
                            </h5>
                            <p class="text-muted">
                                This course is a great way to learn backend development with NODE.JS and Express.
                                Has 5 projects including microservices and a full app as well.
                            </p>
                        </li>
                        <li class="list-group-item">
                            <h5>
                                <a href="https://courses.edx.org/certificates/a13b3a78b3ee4c7687fdedcc628575b2">
                                    CS50x: CS50's Introduction to Computer Science
                                </a>
                            </h5>
                            <p class="text-muted">
                                This course conducted by Haravard University is a great way to learn computer
                                science. Includes C language, Python, SQL, HTML, CSS, Javascript, and more.
                                Datastructures and algorithms, and flask rfamework as well. Each topic has 3 project
                                and one final project at the end of the course.
                            </p>
                        </li>
                        <li class="list-group-item">
                            <h5>
                                <a href="https://courses.edx.org/certificates/649f924942564c8094af505d8acb6217">
                                    PH125.2x: Data Science: Visualization
                                </a>
                            </h5>
                            <p class="text-muted">
                                This course conducted by Harvard University is a great way to learn data science
                                with R language. The course makorly focuses on data Visualization.
                            </p>
                        </li>

                    </ul>
                    <br>
                    <br>
                    <br>
                    <p>
                        <strong>Email:</strong> <a href="mailto:shrey1098@hotmail.com">shrey1098@hotmail.com</a>
                    </p>
                    <p>
                        <strong>Github:</strong> <a href="https://github.com/shrey1098"
                            target="_blank">shrey1098</a>
                    </p>
                    <p>
                        <strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/shrey-sharma-163626147/"
                            target="_blank">Shrey Sharma</a>
                    </p>
                    </p>
                </div>
            </div>
            <!-- end of card -->
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>

<br>

{%endblock%}

templates/docs.html
{% extends 'layout.html'%}
{% block content %}
<div class="container" style="margin-top: 5vh">
    <!-- side navigation-->
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="#" class="list-group-item list-group-item-action active">
                    API Endpoints
                </a>
                <a href="#" class="list-group-item list-group-item-action" name="init"
                    onclick="show(name), hide(name)">/rest/v1/calendar/init</a>
                <a href="#" class="list-group-item list-group-item-action" name="redirect"
                    onclick="show(name), hide(name)">/rest/v1/calendar/redirect</a>
            </div>
        </div>
        <!-- body for main content of each endpoint-->
        <div class="col-md-9">
            <div class="card" id="init" style="display: block">
                <div class="card-body">
                    <h5 class="card-title">/rest/v1/calendar/init</h5>
                    <p class="card-text">
                        This endpoint is used to get the authorization code from google.
                        The authorization code is used to get the access token.
                        The access token is used to get the events from google calendar.
                        And redirected to get list of events
                    </p>
                    <br>
                    <br>
                    <a href="{% url 'api:register' %}" class="btn btn-primary">Try it</a>
                </div>
            </div>
            <div class="card" id="redirect" style="display: none">
                <div class="card-body">
                    <h5 class="card-title">/rest/v1/calendar/redirect</h5>
                    <p class="card-text">
                        This endpoint is used to get the access token from google.
                        The access token is used to get the events from google calendar.
                    </p>
                    <br>
                    <br>
                    <p>Sample Response:</p>
                    <code>
                        {
                            date: event
                        }
                    </code>
                    <br>
                    <br>
                    <a href="{% url 'api:register' %}" class="btn btn-primary">Try it</a>

                </div>
            </div>
    </div>
</div>
<script>
    function show(name) {
        var x = document.getElementById(name);
        if (x.style.display === "none") {
            x.style.display = "block";
        }
    }
    function hide(name) {
        // function to hide the divs other the one clicked
        var x = document.getElementById(name);
        const arr = ['init', 'redirect'];
        for (var i = 0; i < arr.length; i++) {
            if (arr[i] != name) {
                var y = document.getElementById(arr[i]);
                y.style.display = "none";
            }
        }

    }
</script>
{% endblock %}

templates/index.html
{% extends 'layout.html'%}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome to Google Calendar API</h1>
        <p class="lead">This is a simple application to get the events from your Google Calendar.</p>
        <hr class="my-4">
        <!--button to go to docs-->
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'api:docs'%}" role="button">Go to docs</a>
        </p>

    </div>
{% endblock %}

templates/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Google Calendar API</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Google Calendar API</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button><div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:index'%}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:docs'%}">Docs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:about'%}">About Developer</a>
            </li>
        </ul>
    </div>
</div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>